Repository BHoM/BHoM_Datasets, pull requests merged in 2020-03, with the labels that each got.

#28 Added source information for US Steel Sections
  DataSets/SectionProperties/US_SteelSections/HP.json
  DataSets/SectionProperties/US_SteelSections/HSS.json
  DataSets/SectionProperties/US_SteelSections/L.json
  DataSets/SectionProperties/US_SteelSections/MT.json
  DataSets/SectionProperties/US_SteelSections/PIPE.json
  DataSets/SectionProperties/US_SteelSections/W.json
  DataSets/SectionProperties/US_SteelSections/WT.json
Labels: type:compliance

#30 Added source to all UK_SteelSections
  DataSets/SectionProperties/UK_SteelSections/CHS.json
  DataSets/SectionProperties/UK_SteelSections/L.json
  DataSets/SectionProperties/UK_SteelSections/Leq.json
  DataSets/SectionProperties/UK_SteelSections/PFC.json
  DataSets/SectionProperties/UK_SteelSections/RHS.json
  DataSets/SectionProperties/UK_SteelSections/SHS.json
  DataSets/SectionProperties/UK_SteelSections/TUB.json
  DataSets/SectionProperties/UK_SteelSections/TUC.json
  DataSets/SectionProperties/UK_SteelSections/UB.json
  DataSets/SectionProperties/UK_SteelSections/UBP.json
  DataSets/SectionProperties/UK_SteelSections/UC.json
Labels: type:compliance

#29 Adding source to EU material Datasets
  DataSets/Materials/MaterialsEurope/Concrete.json
  DataSets/Materials/MaterialsEurope/Rebar.json
  DataSets/Materials/MaterialsEurope/Steel(Grade).json
  DataSets/Materials/MaterialsEurope/Steel.json
Labels: type:compliance

#34 Add Source to US Materials datasets
  DataSets/Materials/MaterialsUSA/Concrete.json
  DataSets/Materials/MaterialsUSA/Steel.json
Labels: size:S, type:compliance

#36 Fixing correct scale factor for warping constants
  DataSets/SectionProperties/UK_SteelSections/UB.json
  DataSets/SectionProperties/UK_SteelSections/UBP.json
  DataSets/SectionProperties/UK_SteelSections/UC.json
Labels: type:bug

#38 Add Inventory of Carbon and Energy Datasets
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Aggregates.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Aluminum.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Asphalt.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Bitumen.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_CementMortar.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_ClayBricks.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Concrete.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Glass.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Steel.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_TimberExcludingStorage.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_TimberIncludingStorage.json
Labels: type:feature
